version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo

  myapp:
    image: gcr.io/OnlyTangs/webapp:v1
    build: .
    container_name: myapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/myapp
      - GOOGLE_APPLICATION_CREDENTIALS=./onlytangs-2cba7775d004.json
    depends_on:
      - mongo