version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db  # Map the host directory `./data` to the container directory `/data/db`

  myapp:
    build: .
    container_name: myapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/myapp
    depends_on:
      - mongo